"""Add material_name to raw_materials

Revision ID: f5a2d35b7a0d
Revises: 43d979394022
Create Date: 2024-10-10 03:26:32.543952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5a2d35b7a0d'
down_revision: Union[str, None] = '43d979394022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_materials', sa.Column('material_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_raw_materials_material_name'), 'raw_materials', ['material_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_materials_material_name'), table_name='raw_materials')
    op.drop_column('raw_materials', 'material_name')
    # ### end Alembic commands ###
